language: php
php:
  - 5.4
before_script:
  - cd ~/builds
  - git clone --quiet git://github.com/silverstripe/silverstripe-installer.git ss3
  - cd ~/builds/ss3
  - git clone git://github.com/silverstripe/sapphire.git framework
  - git clone git://github.com/silverstripe/silverstripe-cms.git cms
  - git clone git://github.com/silverstripe-themes/silverstripe-simple.git themes/simple
  - cd ~/builds
  - mv yukiawano/sscpmodule ss3/sscp
  - mysql -e "create database IF NOT EXISTS ss_module_test;"
  - mv -f ss3/sscp/tests/travis/_config.php.travis ss3/mysite/_config.php
  - mv -f ss3/sscp/tests/travis/_ss_environment.php.travis ss3/_ss_environment.php
  - cd ss3/framework
  - ./sake dev/build "flush=1"
script:
  - ./sake dev/tests/module/sscp "flush=1"
